package repocheck

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"unicode"
)

const (
	RequiredName         = "Oleksii Stupin"
	RequiredEmail        = "oleksii.stupin@gmail.com"
	githubCommitterName  = "GitHub"
	githubCommitterEmail = "noreply@github.com"
)

// Commit contains the attribution fields protected by repository policy.
type Commit struct {
	Hash           string
	AuthorName     string
	AuthorEmail    string
	CommitterName  string
	CommitterEmail string
	Message        string
}

// ValidateCommit requires the exact author and committer identity and a clean message.
func ValidateCommit(commit Commit, allowGitHubCommitter bool) error {
	var problems []error
	if commit.AuthorName != RequiredName || commit.AuthorEmail != RequiredEmail {
		problems = append(problems, fmt.Errorf("commit %s author is %s <%s>", commit.Hash, commit.AuthorName, commit.AuthorEmail))
	}
	validCommitter := commit.CommitterName == RequiredName && commit.CommitterEmail == RequiredEmail
	githubCommitter := commit.CommitterName == githubCommitterName && commit.CommitterEmail == githubCommitterEmail
	if !validCommitter && !(allowGitHubCommitter && githubCommitter) {
		problems = append(problems, fmt.Errorf("commit %s committer is %s <%s>", commit.Hash, commit.CommitterName, commit.CommitterEmail))
	}
	if forbidden := ForbiddenAttribution(commit.Message); forbidden != "" {
		problems = append(problems, fmt.Errorf("commit %s message contains forbidden attribution %q", commit.Hash, forbidden))
	}

	return errors.Join(problems...)
}

// ForbiddenAttribution returns the forbidden attribution token found in text.
func ForbiddenAttribution(text string) string {
	lower := strings.ToLower(text)
	for _, phrase := range []string{"co-authored-by", "generated-by", "generated by"} {
		if strings.Contains(lower, phrase) {
			return phrase
		}
	}
	for _, word := range strings.FieldsFunc(lower, func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r) && r != '_'
	}) {
		if word == "bot" || word == "assistant" {
			return word
		}
	}
	return ""
}

// LoadCommits reads real commits selected by a constrained Git revision expression.
func LoadCommits(ctx context.Context, root, revision string) ([]Commit, error) {
	if err := validateRevision(revision); err != nil {
		return nil, err
	}

	output, err := run(ctx, root, "git", "rev-list", revision, "--")
	if err != nil {
		return nil, fmt.Errorf("list commits: %w", err)
	}
	hashes := strings.Fields(string(output))
	if len(hashes) == 0 {
		return nil, fmt.Errorf("revision %q selects no commits", revision)
	}

	commits := make([]Commit, 0, len(hashes))
	for _, hash := range hashes {
		commit, err := loadCommit(ctx, root, hash)
		if err != nil {
			return nil, err
		}
		commits = append(commits, commit)
	}
	return commits, nil
}

func validateRevision(revision string) error {
	if revision == "" || strings.HasPrefix(revision, "-") {
		return fmt.Errorf("invalid revision expression %q", revision)
	}
	for _, r := range revision {
		if unicode.IsLetter(r) || unicode.IsDigit(r) || strings.ContainsRune("._/~^@{}+-", r) {
			continue
		}
		return fmt.Errorf("invalid character in revision expression %q", revision)
	}
	return nil
}

func loadCommit(ctx context.Context, root, hash string) (Commit, error) {
	format := "format:%H%x00%an%x00%ae%x00%cn%x00%ce%x00%B%x00"
	output, err := run(ctx, root, "git", "show", "-s", "--no-show-signature", "--format="+format, hash, "--")
	if err != nil {
		return Commit{}, fmt.Errorf("inspect commit %s: %w", hash, err)
	}
	fields := bytes.Split(output, []byte{0})
	if len(fields) < 7 {
		return Commit{}, fmt.Errorf("inspect commit %s: unexpected Git output", hash)
	}
	return Commit{
		Hash:           string(fields[0]),
		AuthorName:     string(fields[1]),
		AuthorEmail:    string(fields[2]),
		CommitterName:  string(fields[3]),
		CommitterEmail: string(fields[4]),
		Message:        string(fields[5]),
	}, nil
}

// CheckAutomation scans release automation without following symlinks.
func CheckAutomation(root string) error {
	paths := []string{filepath.Join(root, ".github"), filepath.Join(root, "scripts")}
	for _, path := range paths {
		if _, err := os.Lstat(path); errors.Is(err, fs.ErrNotExist) {
			continue
		} else if err != nil {
			return fmt.Errorf("inspect automation root %s: %w", path, err)
		}
		if err := filepath.WalkDir(path, func(path string, entry fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			info, err := entry.Info()
			if err != nil {
				return err
			}
			if info.Mode()&os.ModeSymlink != 0 {
				return fmt.Errorf("automation path %s is a symlink", path)
			}
			if entry.IsDir() {
				return nil
			}
			if !info.Mode().IsRegular() || info.Size() > 1<<20 {
				return fmt.Errorf("automation path %s is not a bounded regular file", path)
			}
			contents, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			if forbidden := ForbiddenAttribution(string(contents)); forbidden != "" {
				return fmt.Errorf("automation path %s contains forbidden attribution %q", path, forbidden)
			}
			return nil
		}); err != nil {
			return err
		}
	}
	return nil
}

func run(ctx context.Context, dir, name string, args ...string) ([]byte, error) {
	command := exec.CommandContext(ctx, name, args...)
	command.Dir = dir
	output, err := command.CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("%s %s: %w\n%s", name, strings.Join(args, " "), err, bytes.TrimSpace(output))
	}
	return output, nil
}
